const state = {
  items: [
    {
      id: "001-beetroot",
      name: "beetroot",
      price: 0.4,
      quantity: 1,
      type: "vegetable",
    },
    {
      id: "002-carrot",
      name: "carrot",
      price: 0.25,
      quantity: 1,
      type: "vegetable",
    },
    {
      id: "003-apple",
      name: "apple",
      price: 0.33,
      quantity: 1,
      type: "fruit",
    },
    {
      id: "004-apricot",
      name: "apricot",
      price: 0.39,
      quantity: 1,
      type: "fruit",
    },
    {
      id: "005-avocado",
      name: "avocado",
      price: 0.65,
      quantity: 1,
      type: "fruit",
    },
    {
      id: "006-bananas",
      name: "bananas",
      price: 0.43,
      quantity: 1,
      type: "fruit",
    },
    {
      id: "007-bell-pepper",
      name: "bell pepper",
      price: 0.55,
      quantity: 1,
      type: "fruit",
    },
    {
      id: "008-cherry",
      name: "cherry",
      price: 0.15,
      quantity: 1,
      type: "fruit",
    },
    {
      id: "009-blueberry",
      name: "blueberry",
      price: 0.05,
      quantity: 1,
      type: "fruit",
    },
    {
      id: "010-eggplant",
      name: "eggplant",
      price: 0.35,
      quantity: 1,
      type: "vegetable",
    },
  ],
  cart: [],
};
